server:
  port: ${PORT:8080}

test-1: Test
test-2: 10MB

spring:
  mvc:
    async:
      request-timeout: 80000
      test-1: Qwerty
      test-2: Qwerty
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  http:
    log-request-details: true
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  codec:
    max-in-memory-size: -1

logging:
  level:
    org.springframework.web:
      server.adapter.HttpWebHandlerAdapter: TRACE
      HttpLogging: TRACE
      reactive.function.client.ExchangeFunctions: TRACE
    com.bs2.phoenix.api: DEBUG
    root: INFO
  file:
    name: ${LOGS_DIRECTORY:logs}/phoenix.log
    max-history: 30
    max-size: 10MB
  pattern:
    dateformat: dd-MM-yyyy HH:mm:ss.SSS, Europe/Minsk
    rolling-file-name: ${LOGS_DIRECTORY:logs}/archived/phoenix.%d{dd-MM-yyyy}.%i.log

service:
  tickets-service-url: ${TICKETS_SERVICE_URL:http://localhost:9085}
  dashboard-service-url: ${TICKETS_SERVICE_URL:http://localhost:9085}
  vault-service-url: ${DASHBOARD_SERVICE_URL:http://localhost:9086}
  geo-service-url: ${GEO_SERVICE_URL:http://localhost:9087}
  form-config-service-url: ${FORM_CONFIG_SERVICE_URL:http://localhost:9088}
