version: "3.7"
services:
  link-shortener-service:
    build: .
    image: link-shortener:latest
    container_name: link-shortener-service
    restart: on-failure
    working_dir: /var/www/link_shortener
    environment:
      POSTGRES_DB_HOST: postgres-service
      POSTGRES_DB_PORT: 5432
      POSTGRES_DB_NAME: link_shortener
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      CURRENT_DOMAIN: "http://localhost"
    volumes: ./:/var/www/link_shortener
    networks: link-shortener-network
    depends_on: postgres-service
  nginx-service:
    image: nginx:1.18.0-alpine
    container_name: nginx-service
    restart: on-failure
    ports: 80:80
    volumes: ./:/var/www/link_shortener
    networks: link-shortener-network
    depends_on: link-shortener-service
  postgres-service:
    image: postgres:12.0
    container_name: postgres-service
    restart: on-failure
    ports: 5432
    environment:
      POSTGRES_DB: link_shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes: postgres-link-shortener-data:/var/lib/postgresql/data
    networks: link-shortener-network
networks:
  link-shortener-network:
    driver: bridge
